name: release
on:
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install deps
        run: npm ci
      - name: Build 
        run: npm run electron:build -- -p always
      - name: Make zip
        run: 7z a emoji-folder-structure.zip dist_electron -r
      - name: ls
        run: ls -l
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: emoji-folder-structure.zip